PRAGMA FOREIGN_KEYS = ON;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS games;

CREATE TABLE games (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR NOT NULL UNIQUE,
	min_players INTEGER NOT NULL,
	max_players INTEGER NOT NULL,
	category VARCHAR(50) NOT NULL DEFAULT 'other',
	cost DECIMAL(5,2) NOT NULL,
	avg_playtime INTEGER, -- represents num minutes
	min_age INTEGER NOT NULL
);

CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	birthdate DATETIME NOT NULL,
	username VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	fave_game_id INTEGER REFERENCES games(id) ON DELETE SET NULL
	-- fave_game_id INTEGER,
	-- FOREIGN KEY(fave_game_id) REFERENCES games(id)
);

CREATE TABLE reviews (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	rating INTEGER NOT NULL,
	complexity INTEGER NOT NULL,
	content TEXT NOT NULL,
	game_id INTEGER REFERENCES games(id) ON DELETE CASCADE,
	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE likes (
	id INTEGER PRIMARy KEY AUTOINCREMENT,
	review_id INTEGER REFERENCES reviews(id),
	user_id INTEGER REFERENCES users(id),
	like BOOLEAN
);